config/routes.rb
Rails.application.routes.draw do
  root to: 'oauth_test#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    # この記述を追記
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :events
  resources :blogs
  resources :questions
  resources :profiles
  post "/profiles/new" => 'profiles#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable, omniauth_providers: %i(google)

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/oauth_test_controller.rb
class OauthTestController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @user = User.all
  end
  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to profiles_path
    else
      render :new
    end
  end
    
  def show
    @user = User.find(params[:id])
  end
    
      private
      
      def user_params
        params.require(:user).permit(:nickname, :image, :gender, :introduction,
                                     :age, :image_cache, :id)
      end
      def set_user
        @user = User.find(params[:id])
      end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google
      @user = User.find_for_google(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "google") if is_navigational_format?
      else
        session['devise.google_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
  def build_resource(hash={})
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/oauth_test_helper.rb
module OauthTestHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/oauth_test/index.html.erb
<p><%= notice %><%= alert %></p>
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Googleでサインアップしてね', user_google_omniauth_authorize_path %>
<% end %>

<% if user_signed_in? %>
<% unless current_user.nickname.present? %>
<%= link_to 'プロフィールを作成する', new_profile_path %>
<% end %>
<% end %>

<% if user_signed_in? && current_user.nickname.present? %>
<%= link_to 'イベントを見る', events_path %>
<%= link_to 'プロフィール詳細を見る', profile_path(current_user.id) %>
<%= link_to 'Q & A コーナーを見る', questions_path %>
<% end %>

app/views/profiles/index.html.erb
あ

app/views/profiles/new.html.erb
<h2>プロフィール作成</h2>
  <%= form_with(model: @profile, url: profiles_path, local: true) do |f| %>
    <div class="field">
      <%= f.label :ニックネーム %>
      <%= f.text_field :nickname %>
    </div>

  <div class="field">
    <%= f.label :年齢 %>
    <%= f.select :age, [['２０代', '２０代'], ['３０代', '３０代'],  ['４０代', '４０代'], ['５０代以上', '５０代以上']] %>
  </div>
  
  <div class="field">
  <%= f.label :性別 %>
  <div class="radio-inline">
    <%= f.radio_button :gender, :男性, checked: "checked" %>
    <%= f.label :男性, class: "gender_label" %>
  </div>
  
  <div class="radio-inline">
    <%= f.radio_button :gender, :女性 %>
    <%= f.label :女性, class: "gender_label" %>
  </div>
 
  <div class="field">
    <%= f.label :自由記入欄 %>
    <%= f.text_area :introduction %>
  </div>
 
  <div class="field">
    <%= f.label :プロフィール画像 %>
    <p class="profile"><%= f.file_field :image %></p>
  </div>
 
  <div class="action field">
    <%= f.submit '登録' %>
  </div>

  <% end %>